### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by onilton** [Nycto/Hasher#14]
Would it be possible to add scala.js support?

**Comment by Nycto** [comment]
Hmmm. I'm highly doubtful this could really work. This library doesn't implement the hashing algorithms, it just provides a unified interface for working with various other mechanisms. So to get this to work, the first step would be to actually implement or pull in a JS dependency that implements each algorithm. In and of itself, that's a HUGE change to the nature of this lib.

But because we're dealing with JS, you wouldn't really want that to do that anyway because of how big it would become.  You would need to pull in code for each of the 12 different algorithms, which would make this library way too big for someone who just wants to use one of those libs.

I would entertain a pull request if you could solve the size problem without drastically changing things, but otherwise I'm going to resolve this as `won't implement`.
